### ISSUE TITLE
¿Y las menciones a los creadores originales?

### ISSUE THREAD

**Issue by ManuelJSD** [joaquinodz/Launcher-C#6]
Me parece que les falto mencionar que este Launcher esta basado en un prototipo que desarrollo el Staff de Winter AO basado a su vez en un Launcher creado por Abusivo:

Repositorio **original** del launcher en el que se basaron: https://github.com/Lorwik/Launcher-Update-C-

Repositorio **original** del launcher de Abusivo: https://github.com/abusiv0/AOLibreLauncher

Commit donde reemplazaron el nombre de "Winter AO Resurrection": https://github.com/ao-org/argentum20-lanzador/commit/711b6379b75004ac99a6e79cc2dcda88d4a3e3ba

**Comment by morgolock** [comment]
Hola,

AO20 no usa ningun launcher. Este repo no se usa para nada y lo vamos a borrar.

Si queres envia un pull request agregando los creditos pero creo que vamos a borrar el repo ya que no usamos esto.
